package com.bob.rules.reguralrule

import com.bob.rules.reguralrule.Account;
import com.bob.rules.reguralrule.CashFlow;
import com.bob.rules.reguralrule.AccountPeriod;
import com.bob.rules.reguralrule.CashFlowType;

dialect  "mvel"

rule "increase balance for credits"
when
  ap : AccountPeriod( )
  $acc : Account( )
  cf : CashFlow( type == CashFlowType.CREDIT,
            accountNo == $acc.accountNo,
            date >= ap.start && <= ap.send )
then
  $acc.balance = $acc.balance + cf.amount;
end

rule "Decrease balance for AccountPeriod Debits"
when
   ap : AccountPeriod( )
   $acc : Account( )
   cf : CashFlow( type == CashFlowType.DEBIT, accountNo == $acc.accountNo, date >= ap.start && <= ap.send )
then
   $acc.balance = $acc.balance - cf.amount;
end

rule "Print blance for AccountPeriod" salience - 50
when
   ap : AccountPeriod()
   $acc : Account( )
then
   System.out.println( "Account Number " + $acc.accountNo + " balance " + $acc.balance );
end